var options = [
  {
    label: "Head",
    type: "top",
    attribute: "topType",
    values: [
      "NoHair",
      "LongHairBigHair",
      "LongHairBob",
      "LongHairBun",
      "LongHairCurly",
      "LongHairCurvy",
      "LongHairDreads",
      "LongHairFro",
      "LongHairNotTooLong",
      "LongHairMiaWallace",
      "LongHairStraight",
      "LongHairStraight2",
      "LongHairStraightStrand",
      "ShortHairDreads01",
      "ShortHairDreads02",
      "ShortHairFrizzle",
      "ShortHairShaggyMullet",
      "ShortHairShortCurly",
      "ShortHairShortFlat",
      "ShortHairShortRound",
      "ShortHairShortWaved",
      "ShortHairSides",
      "ShortHairTheCaesar",
      "ShortHairTheCaesarSidePart",
    ],
    colorAttribute: "hairColor",
    colors: {
      Auburn: "#A55728",
      Black: "#2C1B18",
      Blonde: "#B58143",
      BlondeGolden: "#D6B370",
      Brown: "#724133",
      BrownDark: "#4A312C",
      PastelPink: "#F59797",
      Platinum: "#ECDCBF",
      Red: "#C93305",
      SilverGray: "#E8E1E1",
    },
    hats: [
      "Hat",
      "Hijab",
      "Turban",
      "WinterHat1",
      "WinterHat2",
      "WinterHat3",
      "WinterHat4",
    ],
    hatColors: {
      Black: "#262E33",
      Blue01: "#65C9FF",
      Blue02: "#5199E4",
      Blue03: "#25557C",
      Gray01: "#E6E6E6",
      Gray02: "#929598",
      Heather: "#3C4F5C",
      PastelBlue: "#B1E2FF",
      PastelGreen: "#A7FFC4",
      PastelOrange: "#FFDEB5",
      PastelRed: "#FFAFB9",
      PastelYellow: "#FFFFB1",
      Pink: "#FF488E",
      Red: "#FF5C5C",
      White: "#FFFFFF",
    },
  },
  {
    label: "Accessories",
    type: "accessories",
    attribute: "accessoriesType",
    values: [
      "Blank",
      "Kurt",
      "Prescription01",
      "Prescription02",
      "Round",
      "Sunglasses",
      "Wayfarers",
    ],
  },
  {
    label: "Skin",
    type: "skinColor",
    attribute: "skinColor",
    values: [],
    colorAttribute: "skinColor",
    colors: {
      Tanned: "#FD9841",
      Yellow: "#F8D25C",
      Pale: "#FFDBB4",
      Light: "#EDB98A",
      Brown: "#D08B5B",
      DarkBrown: "#AE5D29",
      Black: "#614335",
    },
  },
];

export default options;
